 export const studentDesignedProjects = [{
        "title": "Teaching Responsible Computing (RC) Through Designing Robotics Applications to Kenyan Computer Science Students",
        "description": "<p>JKUAT received a 2023 Responsible Computing Challenge (RCC) award from the Mozilla Foundation to train and embed ethical considerations into the development of robotics.</p>\n\n<p> <a href='https://foundation.mozilla.org/en/blog/announcing-kenyas-inaugural-cohort-of-responsible-computing-challenge-awardees/' target='_blank' class='text-blue-600 hover:underline'><strong>RCC Computing Challenge Award</strong></a></p>\n\n<p>This project focuses on teaching responsible computing through designing robot applications. The goal is to provide students with practical experiences where they collaboratively apply their responsible computing knowledge and ethical awareness to design and develop responsible robotic applications. Through this initiative, we have developed a model syllabus for a human-computer interaction course that integrates design and responsible computing. The User Interface Architecture syllabus was adopted for BSc Computer Science and Computer Technology courses, and the RCC project led to the mainstreaming of responsible computing (RC) in final-year projects by revising guidelines to include RC and ethics. The project trained 112 students, involved 13 stakeholders, and developed 27 robot prototypes, with plans to sustain RCC through eLearning content and further integration of RC into student projects and departmental innovations. This project is led by Dr Eunice Njeri, lecturer in the Department of Computing, and Prof. Stephen Kimani, associate professor of Human-Computer interaction in the Department of Computing with the support of four MSc software engineering students - Peter Kabunyi, Caroline Katumbi, Paul Ndemo, and Eric Otieno.</p>\n\n<p><a href='https://youtu.be/0Poy3Iavmeg' target='_blank' class='text-blue-600 hover:underline'>Click here to know more about this project</a></p>\n\n<strong>The JKUAT RCC Project is funded by the Mozilla Foundation and USAID. </strong>",       "short_description": "<p>JKUAT received a 2023 Responsible Computing Challenge (RCC) award from the Mozilla Foundation to train and embed ethical considerations into the development of robotics.</p>\n\n<p> <a href='https://foundation.mozilla.org/en/blog/announcing-kenyas-inaugural-cohort-of-responsible-computing-challenge-awardees/' target='_blank' class='text-blue-600 hover:underline'><strong>RCC Computing Challenge Award</strong></a></p>\n\n<p>This project focuses on teaching responsible computing through designing robot applications.  ",
        "cover_image": "/img/projects/teaching-rc.png",
        "category": "P"
   
    },
    {
        "title": "Mainstreaming Responsible Computing (RC) in ICT Student Innovations - with a Focus on Final Year ICT Student Projects",
        "description": "The first part of this project aims to integrate responsible computing (RC) and ethics in the design process of final-year student ICT Innovations. The second part involves integrating RC and ethics in the assessment criteria and supervision of final-year student projects. We have trained (n = 100) BSc. Computer Science and BSc. Computer Technology on responsible computing (RC) and ethics. We have also taught (n = ~ 15) faculty and (n = 20) postgraduate students at the School of Computing and Information Technology  (SCIT) on RC and ethics. The project is led by Dr. Eunice Njeri and Prof. Stephen Kimani, Department of Computing with the support of MSc Software Engineering students - Peter Kabunyi, Caroline Katumbi, Paul Ndemo, and Eric Otieno.",
        "short_description": "The first part of this project aims to integrate responsible computing (RC) and ethics in the design process of final-year student ICT Innovations. The second part involves integrating RC and ethics in the assessment criteria and supervision of final-year student projects. We have trained (n = 100) BSc. Computer Science and BSc. Computer Technology on responsible computing (RC) and ethics. We have also taught (n = ~ 15) faculty and (n = 20) postgraduate students at the School of Computing and Information Technology  (SCIT) on RC and ethics. The project is led by Dr. Eunice Njeri and Prof. Stephen Kimani, Department of Computing with the support of MSc Software Engineering students - Peter Kabunyi, Caroline Katumbi, Paul Ndemo, and Eric Otieno. ",
        "cover_image": "/img/projects/mainstreaming-rc.png",
        "category": "P"
  
    },
    {
        "title": "Design and Use a Responsible Computing Industry-led Final-year Project Framework.",
        "description": "The project aims to examine past Final Year computing projects with the intention of building a responsible computing framework for future ICT projects, with input from industry stakeholders. This project aims to further integrate responsible computing into final-year ICT projects by developing an RC framework, training faculty, and guiding students in applying these principles. We will also engage stakeholders, expand the initiative to other programs, and develop a software tool to support the RC framework implementation.This project is led by Dr Eunice Njeri, lecturer in the Department of Computing, and Prof. Stephen Kimani, associate professor of Human-Computer interaction in the Department of Computing with the support of  Dr Isaac Oteyo and four MSc software engineering students - Peter Kabunyi, Caroline Katumbi, Paul Ndemo, and Eric Otieno.",
        "short_description": "The project aims to examine past Final Year computing projects with the intention of building a responsible computing framework for future ICT projects, with input from industry stakeholders. This project aims to further integrate responsible computing into final-year ICT projects by developing an RC framework, training faculty, and guiding students in applying these principles. We will also engage stakeholders, expand the initiative to other programs, and develop a software tool to support the RC framework implementation. ",
        "cover_image": "/img/projects/mainstreaming-rc.png",
        "category": "P"
  
    }
]